In [196]:
import pandas as pd
import nltk
import numpy as np
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords
import string
# from langdetect import detect
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\marti\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\marti\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\marti\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\marti\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [197]:
df = pd.read_csv("data\df_limpio.csv")

In [198]:
len(df)

6871

Nos quedamos solo con las reviews y la url como identificador

In [199]:
df[["url", "review_0", "review_1"]].isnull().sum()

url            0
review_0    1202
review_1    1774
dtype: int64

Eliminamos las filas que no tengan ninguna review

In [200]:
df.dropna(subset=['review_0'], inplace=True)

In [201]:
df[["url", "review_0", "review_1"]].head()

url  \
0  /Restaurant_Review-g312741-d26322909-Reviews-C...   
1  /Restaurant_Review-g312741-d15325004-Reviews-F...   
2  /Restaurant_Review-g312741-d8696562-Reviews-Ar...   
3  /Restaurant_Review-g312741-d25279370-Reviews-F...   
4  /Restaurant_Review-g312741-d25198242-Reviews-I...   

                                            review_0  \
0      Amazing, highly recommend this experience!!!!   
1  I took my wife and two grown up children for d...   
2  We found the Argentine Experience to be exactl...   
3                    Experiencia Inmersiva Excelente   
4  My husband had the cantelonni stuffed with la...   

                                      review_1  
0                       Cooking with Johnathon  
1                             A great evening.  
2  The steak was beyond delicious and the...  
3                  Amazing place great service  
4             Great food and nice food place

Por hacer: detección de lenguaje

In [202]:
def detect_language(text):
    try:
        language = detect(text)
        return language
    except Exception as e:
        print(f"Error al detectar el idioma: {e}")
        return "No detectado"

In [203]:
# df["review_0"] = df["review_0"].astype(str)
# df["review_1"] = df["review_1"].astype(str)

In [204]:
# df['language_0'] = df['review_0'].apply(detect_language)
# df['language_1'] = df['review_1'].apply(detect_language)

Tokenización

In [205]:
df["review_0_token"] = df["review_0"].apply(lambda x: nltk.word_tokenize(str(x)))
df["review_1_token"] = df["review_1"].apply(lambda x: nltk.word_tokenize(str(x)))

In [206]:
df[[ "review_0", "review_1", "review_0_token", "review_1_token"]].head()

review_0  \
0      Amazing, highly recommend this experience!!!!   
1  I took my wife and two grown up children for d...   
2  We found the Argentine Experience to be exactl...   
3                    Experiencia Inmersiva Excelente   
4  My husband had the cantelonni stuffed with la...   

                                      review_1  \
0                       Cooking with Johnathon   
1                             A great evening.   
2  The steak was beyond delicious and the...   
3                  Amazing place great service   
4             Great food and nice food place   

                                      review_0_token  \
0  [Amazing, ,, highly, recommend, this, experien...   
1  [I, took, my, wife, and, two, grown, up, child...   
2  [We, found, the, Argentine, Experience, to, be...   
3                [Experiencia, Inmersiva, Excelente]   
4  [My, husband, had, the, cantelonni, stuffed, w...   

                                      review_1_token  
0                         [Cooking, with, Johnathon]  
1                             [A, great, evening, .]  
2  [The, steak, was, beyond, delicious, and, th...  
3                   [Amazing, place, great, service]  
4            [Great, food, and, nice, food, place]

Eliminación de mayúsculas

In [207]:
df["review_0_token"] = df["review_0_token"].apply(lambda x: [el.lower() for el in x])
df["review_1_token"] = df["review_1_token"].apply(lambda x: [el.lower() for el in x])

In [208]:
df[[ "review_0", "review_1", "review_0_token", "review_1_token"]].head()

review_0  \
0      Amazing, highly recommend this experience!!!!   
1  I took my wife and two grown up children for d...   
2  We found the Argentine Experience to be exactl...   
3                    Experiencia Inmersiva Excelente   
4  My husband had the cantelonni stuffed with la...   

                                      review_1  \
0                       Cooking with Johnathon   
1                             A great evening.   
2  The steak was beyond delicious and the...   
3                  Amazing place great service   
4             Great food and nice food place   

                                      review_0_token  \
0  [amazing, ,, highly, recommend, this, experien...   
1  [i, took, my, wife, and, two, grown, up, child...   
2  [we, found, the, argentine, experience, to, be...   
3                [experiencia, inmersiva, excelente]   
4  [my, husband, had, the, cantelonni, stuffed, w...   

                                      review_1_token  
0                         [cooking, with, johnathon]  
1                             [a, great, evening, .]  
2  [the, steak, was, beyond, delicious, and, th...  
3                   [amazing, place, great, service]  
4            [great, food, and, nice, food, place]

Eliminación de stop words y signos de puntuación

In [209]:
stopwords_en = stopwords.words('english')
punctuation = string.punctuation

In [210]:
df["review_0_token"] = df["review_0_token"].apply(lambda x: [el for el in x if el not in stopwords_en])
df["review_1_token"] = df["review_1_token"].apply(lambda x: [el for el in x if el not in stopwords_en])

In [211]:
df["review_0_token"] = df["review_0_token"].apply(lambda x: [el for el in x if el not in punctuation])
df["review_1_token"] = df["review_1_token"].apply(lambda x: [el for el in x if el not in punctuation])

In [212]:
df[[ "review_0", "review_1", "review_0_token", "review_1_token"]].head()

review_0  \
0      Amazing, highly recommend this experience!!!!   
1  I took my wife and two grown up children for d...   
2  We found the Argentine Experience to be exactl...   
3                    Experiencia Inmersiva Excelente   
4  My husband had the cantelonni stuffed with la...   

                                      review_1  \
0                       Cooking with Johnathon   
1                             A great evening.   
2  The steak was beyond delicious and the...   
3                  Amazing place great service   
4             Great food and nice food place   

                                      review_0_token  \
0           [amazing, highly, recommend, experience]   
1  [took, wife, two, grown, children, dinner, fog...   
2  [found, argentine, experience, exactly, argent...   
3                [experiencia, inmersiva, excelente]   
4             [husband, cantelonni, stuffed, lamb]   

                       review_1_token  
0                [cooking, johnathon]  
1                    [great, evening]  
2   [steak, beyond, delicious, ...]  
3    [amazing, place, great, service]  
4  [great, food, nice, food, place]

Lematización

In [213]:
lemmatizer = WordNetLemmatizer()

In [214]:
df["review_0_token"] = df["review_0_token"].apply(lambda x: [lemmatizer.lemmatize(el) for el in x])
df["review_1_token"] = df["review_1_token"].apply(lambda x: [lemmatizer.lemmatize(el) for el in x])

In [215]:
df[[ "review_0", "review_1", "review_0_token", "review_1_token"]].head()

review_0  \
0      Amazing, highly recommend this experience!!!!   
1  I took my wife and two grown up children for d...   
2  We found the Argentine Experience to be exactl...   
3                    Experiencia Inmersiva Excelente   
4  My husband had the cantelonni stuffed with la...   

                                      review_1  \
0                       Cooking with Johnathon   
1                             A great evening.   
2  The steak was beyond delicious and the...   
3                  Amazing place great service   
4             Great food and nice food place   

                                      review_0_token  \
0           [amazing, highly, recommend, experience]   
1  [took, wife, two, grown, child, dinner, fogon,...   
2  [found, argentine, experience, exactly, argent...   
3                [experiencia, inmersiva, excelente]   
4             [husband, cantelonni, stuffed, lamb]   

                       review_1_token  
0                [cooking, johnathon]  
1                    [great, evening]  
2   [steak, beyond, delicious, ...]  
3    [amazing, place, great, service]  
4  [great, food, nice, food, place]

Vamos a ver cuales son las palabras que más se repiten

In [216]:
reviews_0 = [item for sublist in df['review_0_token'].tolist() for item in sublist]
reviews_1 = [item for sublist in df['review_1_token'].tolist() for item in sublist]

In [217]:
counts  = nltk.FreqDist(reviews_0+reviews_1)
counts

FreqDist({'...': 2281, 'good': 1053, 'great': 768, 'food': 765, 'de': 709, 'place': 670, 'nan': 572, 'muy': 547, 'service': 442, 'la': 428, ...})

In [218]:
print("Palabras únicas:")
len(counts)

Palabras únicas:


7145

In [219]:
reviews = df['review_0_token'].apply(lambda x: ' '.join(x)) + df['review_1_token'].apply(lambda x: ' '.join(x))

In [220]:
reviews

0       amazing highly recommend experiencecooking joh...
1       took wife two grown child dinner fogon asado l...
2       found argentine experience exactly argentine e...
3       experiencia inmersiva excelenteamazing place g...
4       husband cantelonni stuffed lambgreat food n...
                              ...                        
6151                                   pésima atenciónnan
6320    lovely place quiet cozy french toast ordered d...
6334                        são sucursal villa urquizanan
6592                         neat lord ring themed barnan
6837                                          flawlessnan
Length: 5669, dtype: object

In [221]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel
from pprint import pprint

Matriz de conteo:


In [222]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(reviews)

In [223]:
print("Matriz de Conteo:")
print(X.toarray())
print("Características:")
print(vectorizer.get_feature_names_out())

Matriz de Conteo:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Características:
['00' '03' '10' ... '𝒇𝒂𝒎𝒊𝒍𝒊𝒂' '𝒊𝒓' '𝒑𝒂𝒓𝒆𝒋𝒂']


Ahora vamos a usar TF-IDF:

In [224]:
tf = TfidfVectorizer()
tfidf_matrix = tf.fit_transform(reviews)

In [225]:
tfidf_matrix

<5669x9253 sparse matrix of type '<class 'numpy.float64'>'
	with 40511 stored elements in Compressed Sparse Row format>

In [226]:
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=tf.get_feature_names_out())
print("Matriz TF-IDF:")
print(df_tfidf)

Matriz TF-IDF:
       00   03   10  100  1000normal  1001  100la  100m  100nan  100rico  ...  \
0     0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
1     0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
2     0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
3     0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
4     0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
...   ...  ...  ...  ...         ...   ...    ...   ...     ...      ...  ...   
5664  0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
5665  0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
5666  0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
5667  0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   
5668  0.0  0.0  0.0  0.0         0.0   0.0    0.0   0.0     0.0      0.0  ...   

      오빠닭  최

Vemos algunas columnas:

In [227]:
print(df_tfidf.columns[1000:1100])

Index(['bay', 'bañado', 'bañar', 'baño', 'bañoscalidad', 'bañosmuy', 'bbb',
       'bbq', 'beaf', 'bear', 'beat', 'beaten', 'beautiful', 'beautifull',
       'beautifully', 'beauty', 'bebida', 'became', 'become', 'beef',
       'beeftasty', 'beer', 'beerbasic', 'beercerveceria', 'beercerveja',
       'beerdrink', 'beergood', 'beerhappy', 'beerhidden', 'beerpara',
       'beerpeople', 'beerpong', 'beers', 'beerservice', 'beertastyyyy',
       'beginner', 'behaviour', 'behind', 'bel', 'belgian', 'belgium',
       'belgrano', 'belgranobuena', 'belgranocafetería', 'belgranocaffé',
       'belgranodecent', 'belgranohistórica', 'belgranonan', 'belgranoshame',
       'belgranowent', 'believe', 'bell', 'bella', 'bellagamba', 'belle',
       'bellisimoitalianidad', 'bello', 'belt', 'bem', 'bene', 'benedettan',
       'beneficio', 'benefit', 'benefício', 'benefíciobuena', 'berlinesas',
       'berna', 'bernalelegante', 'bernardo', 'berreta', 'beside', 'besides',
       'best', 'bestbest', 'besth

In [228]:
print(reviews[10])
print(df_tfidf.iloc[9])

greatest parrilla buenos aire im vegetarian ate amazing ask ...amazing service great food
00            0.0
03            0.0
10            0.0
100           0.0
1000normal    0.0
             ... 
𝒄𝒐𝒏           0.0
𝒆𝒏            0.0
𝒇𝒂𝒎𝒊𝒍𝒊𝒂       0.0
𝒊𝒓            0.0
𝒑𝒂𝒓𝒆𝒋𝒂        0.0
Name: 9, Length: 9253, dtype: float64
